title: Zhang Jinhao's Homepage
page-top-title: Zhang Jinhao
top-section-bg-text: Computer Science(Machine Learning)
home-subtitle:  Zhangjinhao 
copyright-text: '&copy; ZhangJinhao 2025-2026. All Rights Reserved.'
